#!/bin/bash -x

# graphe : Infra Projet Lab
# création des netns
ip netns add routA
ip netns add routB
ip netns add rout1
ip netns add rout2
ip netns add poste1
ip netns add poste2
ip netns add poste3
ip netns add poste4


# créer les switches
ovs-vsctl add-br resB
ovs-vsctl add-br resC
ovs-vsctl add-br resD
ovs-vsctl add-br resE
ovs-vsctl add-br internet1

# configuration du routeur A
# créer les liens du routeur A
ip link add routA-eth0 type veth peer name resC-routA
ip link add routA-eth1 type veth peer name internet1-routA
# accrocher les liens au router A
ip link set routA-eth0 netns routA
ip link set routA-eth1 netns routA
# connecter les liens au switch
ovs-vsctl add-port resC resC-routA
ovs-vsctl add-port internet1 internet1-routA
# activer les interface du router A
ip link set dev resC-routA up
ip link set dev internet1-routA up
ip netns exec routA ip link set dev lo up
ip netns exec routA ip link set dev routA-eth0 up
ip netns exec routA ip link set dev routA-eth1 up

# configurer les réseaux sur le router A
ip netns exec routA ip a add dev routA-eth0 172.16.1.254/24
ip netns exec routA ip a add dev routA-eth1 10.87.0.1/24
# activer le routage sur le router A
ip netns exec routA sysctl net.ipv4.conf.all.forwarding=1

#configuration du routeur B
# créer les liens du routeur B
ip link add routB-eth0 type veth peer name resB-routB
ip link add routB-eth1 type veth peer name internet1-routB
# accrocher les liens au router B
ip link set routB-eth0 netns routB
ip link set routB-eth1 netns routB
# connecter les liens au switch
ovs-vsctl add-port resB resB-routB
ovs-vsctl add-port internet1 internet1-routB
# activer les interface du router B
ip link set dev resB-routB up
ip link set dev internet1-routB up
ip netns exec routB ip link set dev lo up
ip netns exec routB ip link set dev routB-eth0 up
ip netns exec routB ip link set dev routB-eth1 up
# configurer les réseaux sur le router B
ip netns exec routB ip a add dev routB-eth0 172.16.1.254/24
ip netns exec routB ip a add dev routB-eth1 10.87.0.2/24
# activer le routage sur le router B
ip netns exec routB sysctl net.ipv4.conf.all.forwarding=1

#configuration du routeur 1
# créer les liens du routeur 1
ip link add rout1-eth0 type veth peer name resC-rout1
ip link add rout1-eth1 type veth peer name resD-rout1
# accrocher les liens au router 1
ip link set rout1-eth0 netns rout1
ip link set rout1-eth1 netns rout1
# connecter les liens au switch
ovs-vsctl add-port resC resC-rout1
ovs-vsctl add-port resD resD-rout1
# activer les interface du router 1
ip link set dev resC-rout1 up
ip link set dev resD-rout1 up
ip netns exec rout1 ip link set dev lo up
ip netns exec rout1 ip link set dev rout1-eth0 up
ip netns exec rout1 ip link set dev rout1-eth1 up
# configurer les réseaux sur le router 1
ip netns exec rout1 ip a add dev rout1-eth0 172.16.1.253/24
# activer le routage sur le router 1
ip netns exec rout1 sysctl net.ipv4.conf.all.forwarding=1

#configuration du routeur 2
# créer les liens du routeur 2
ip link add rout2-eth0 type veth peer name resB-rout2
ip link add rout2-eth1 type veth peer name resE-rout2
# accrocher les liens au router 2
ip link set rout2-eth0 netns rout2
ip link set rout2-eth1 netns rout2
# connecter les liens au switch
ovs-vsctl add-port resB resB-rout2
ovs-vsctl add-port resE resE-rout2
# activer les interface du router 2
ip link set dev resB-rout2 up
ip link set dev resE-rout2 up
ip netns exec rout2 ip link set dev lo up
ip netns exec rout2 ip link set dev rout2-eth0 up
ip netns exec rout2 ip link set dev rout2-eth1 up
# configurer les réseaux sur le router 2
ip netns exec rout2 ip a add dev rout2-eth0 172.16.1.253/24
# activer le routage sur le router 2
ip netns exec rout2 sysctl net.ipv4.conf.all.forwarding=1

# configuration du poste 1
# créer le lien du poste 1
ip link add poste1-eth0 type veth peer name resE-poste1
# accrocher le lien au netns poste 1
ip link set poste1-eth0 netns poste1
# connecter le lien au switch
ovs-vsctl add-port resE resE-poste1
# activer les interface du poste 1
ip netns exec poste1 ip link set dev lo up
ip netns exec poste1 ip link set dev poste1-eth0 up


# configuration du poste 2
# créer le lien du poste 2
ip link add poste2-eth0 type veth peer name resE-poste2
# accrocher le lien au netns poste 2
ip link set poste2-eth0 netns poste2
# connecter le lien au switch
ovs-vsctl add-port resE resE-poste2
# activer les interface du poste 2
ip netns exec poste2 ip link set dev lo up
ip netns exec poste2 ip link set dev poste2-eth0 up


#configuration du poste 3
# créer le lien du poste 3
ip link add poste3-eth0 type veth peer name resD-poste3
# accrocher le lien au netns poste 3
ip link set poste3-eth0 netns poste3
# connecter le lien au switch
ovs-vsctl add-port resD resD-poste3
# activer les interface du poste 3
ip netns exec poste3 ip link set dev lo up
ip netns exec poste3 ip link set dev poste3-eth0 up


#configuration du poste 4
# créer le lien du poste 4
ip link add poste4-eth0 type veth peer name resD-poste4
# accrocher le lien au netns poste 4
ip link set poste4-eth0 netns poste4
# connecter le lien au switch
ovs-vsctl add-port resD resD-poste4
# activer les interface du poste 4
ip netns exec poste4 ip link set dev lo up
ip netns exec poste4 ip link set dev poste4-eth0 up

# ajouter les addr aux router 1 et 2
ip netns exec rout1 ip a add dev rout1-eth1 192.168.100.254/24
ip netns exec rout2 ip a add dev rout2-eth1 192.168.100.253/24


# faire le dnsmasq
#ip netns exec rout1 dnsmasq -d -z -i rout1-eth1 -F 192.168.100.100,192.168.100.150,255.255.255.0

# configurer la route par défaut pour les postes
# ip netns exec poste1 ip r add default via 192.168.100.253
#ip netns exec poste2 ip r add default via 192.168.100.253
#ip netns exec poste3 ip r add default via 192.168.100.254
#ip netns exec poste4 ip r add default via 192.168.100.254
