#!/bin/bash
# efacer les anciennes interfaces
ip netns exec rout1 ip l del rout1-eth1.100
ip netns exec rout1 ip l del rout1-eth1.200

ip netns exec rout2 ip l del rout2-eth1.100
ip netns exec rout2 ip l del rout2-eth1.200

ip netns exec rout1  ip link add mon_tunnel type gretap remote 172.16.2.253 local 172.16.1.253 nopmtudisc
ip netns exec rout1  ip addr add  192.168.100.254/24 dev mon_tunnel
ip netns exec rout1  ip link set mon_tunnel up


ip netns exec rout2  ip link add mon_tunnel type gretap remote 172.16.1.253 local 172.16.2.253 nopmtudisc
ip netns exec rout2  ip addr add  192.168.100.253/24 dev mon_tunnel
ip netns exec rout2  ip link set mon_tunnel up
