#!/bin/bash -x

# Mise en place des Vlans

# ajouter le vlan dans le router 1

ip netns exec rout1 ip link add link rout1-eth1 name rout1-eth1.100 type vlan id 100
ip netns exec rout1 ip link add link rout1-eth1 name rout1-eth1.200 type vlan id 200

# activer l'interface du vlan
ip netns exec rout1 ip link set dev rout1-eth1.100 up
ip netns exec rout1 ip link set dev rout1-eth1.200 up
#
ip netns exec rout1 ip a add dev rout1-eth1.100 192.168.100.254/24 brd +
ip netns exec rout1 ip a add dev rout1-eth1.200 192.168.200.254/24 brd +

ip netns exec rout2 ip link add link rout2-eth1 name rout2-eth1.100 type vlan id 100
ip netns exec rout2 ip link set dev rout2-eth1.100 up
ip netns exec rout2 ip link add link rout2-eth1 name rout2-eth1.200 type vlan id 200
ip netns exec rout2 ip link set dev rout2-eth1.200 up
ip netns exec rout2 ip a add dev rout2-eth1.100 192.168.100.253/24 brd +
ip netns exec rout2 ip a add dev rout2-eth1.200 192.168.200.253/24 brd +

ip netns exec poste1 ip link add link poste1-eth0 name poste1-eth0.100 type vlan id 100
ip netns exec poste1 ip link set poste1-eth0.100 up
ip netns exec poste1 ip a add dev poste1-eth0.100 192.168.100.1/24 brd +

ip netns exec poste2 ip link add link poste2-eth0 name poste2-eth0.200 type vlan id 200
ip netns exec poste2 ip link set poste2-eth0.200 up
ip netns exec poste2 ip a add dev poste2-eth0.200 192.168.200.1/24 brd +

ip netns exec poste3 ip link add link poste3-eth0 name poste3-eth0.100 type vlan id 100
ip netns exec poste3 ip link set poste3-eth0.100 up
ip netns exec poste3 ip a add dev poste3-eth0.100 192.168.100.2/24 brd +

ip netns exec poste4 ip link add link poste4-eth0 name poste4-eth0.200 type vlan id 200
ip netns exec poste4 ip link set poste4-eth0.200 up
ip netns exec poste4 ip a add dev poste4-eth0.200 192.168.200.2/24 brd +
