#!/bin/bash -x

sudo mkdir -p /etc/netns/poste1
sudo mkdir -p /etc/netns/poste2
sudo mkdir -p /etc/netns/poste3
sudo mkdir -p /etc/netns/poste4
sudo mkdir -p /etc/netns/rout1/quagga
sudo mkdir -p /etc/netns/rout2/quagga
sudo mkdir -p /etc/netns/routA/quagga
sudo mkdir -p /etc/netns/routB/quagga


# créer les daemons


sudo cp /home/quimbamba/Documents/Infra/TP/1/daemons /etc/netns/rout1/quagga/
sudo cp /home/quimbamba/Documents/Infra/TP/1/daemons /etc/netns/rout2/quagga/
sudo cp /home/quimbamba/Documents/Infra/TP/1/daemons /etc/netns/routA/quagga/
sudo cp /home/quimbamba/Documents/Infra/TP/1/daemons /etc/netns/routB/quagga/
# le fichier « zebra.conf

sudo cp /usr/share/doc/quagga-core/examples/zebra.conf.sample  /etc/netns/rout1/quagga/zebra.conf
sudo cp /usr/share/doc/quagga-core/examples/zebra.conf.sample  /etc/netns/rout2/quagga/zebra.conf
sudo cp /usr/share/doc/quagga-core/examples/zebra.conf.sample  /etc/netns/routA/quagga/zebra.conf
sudo cp /usr/share/doc/quagga-core/examples/zebra.conf.sample  /etc/netns/routB/quagga/zebra.conf



# le fichier « ripd.conf »

sudo cp /usr/share/doc/quagga-core/examples/ripd.conf.sample  /etc/netns/rout1/quagga/ripd.conf
sudo cp /usr/share/doc/quagga-core/examples/ripd.conf.sample  /etc/netns/rout2/quagga/ripd.conf
sudo cp /usr/share/doc/quagga-core/examples/ripd.conf.sample  /etc/netns/routA/quagga/ripd.conf
sudo cp /usr/share/doc/quagga-core/examples/ripd.conf.sample  /etc/netns/routB/quagga/ripd.conf

# On donne les droits sur le répertoire « quagga » et ses fichiers

sudo chown -R quagga:quagga /etc/netns/rout1/quagga
sudo chown -R quagga:quagga /etc/netns/rout2/quagga
sudo chown -R quagga:quagga /etc/netns/routA/quagga
sudo chown -R quagga:quagga /etc/netns/routB/quagga
